In [4]:
import numpy

In [5]:
numpy.zeros(10)
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
numpy.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

In [7]:
a = numpy.array([1, 2])
a[1]
a[1] = 7
a

array([1, 7])

In [8]:
numpy.arange(5, 10)

array([5, 6, 7, 8, 9])

In [9]:
list(range(5, 10))

[5, 6, 7, 8, 9]

In [10]:
numpy.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [11]:
numpy.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
arr2d = numpy.array([[1, 2, 3], [6, 7, 8]])
arr2d[1][1]

np.int64(7)

In [13]:
arr3d = numpy.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr3d
arr3d.ndim

3

In [14]:
numpy.random.seed(6)
print(numpy.random.rand(2, 3))

[[0.89286015 0.33197981 0.82122912]
 [0.04169663 0.10765668 0.59505206]]


In [15]:
arrObj = numpy.array([1, 2, 3, 0], "S")
arrDataType = arrObj.dtype
print(arrDataType)
arrObjInt = arrObj.astype(bool)
print(arrObjInt)

|S1
[ True  True  True  True]


In [16]:
# Operations
arrObj = numpy.array([1, 2, 3])
arrObj + 1

array([2, 3, 4])

In [17]:
print(arrObj)
arrObj >= 2

[1 2 3]


array([False,  True,  True])

In [18]:
arrObj[arrObj >= 2]

array([2, 3])

In [19]:
arrObj.min()

np.int64(1)

In [20]:
arrObj = numpy.array([1, 2, 3])
arrObj2 = arrObj.copy()
arrObj[0] = 4
print(arrObj.base, arrObj2.base)

None None


In [21]:
arrObj = numpy.array([1, 2, 3])

arrObj2 = arrObj.view()

print(arrObj.base, arrObj2.base)

None [1 2 3]


In [22]:
%whos

Variable      Type          Data/Info
-------------------------------------
I             ndarray       3x3: 9 elems, type `float64`, 72 bytes
a             ndarray       2: 2 elems, type `int64`, 16 bytes
arr2d         ndarray       2x3: 6 elems, type `int64`, 48 bytes
arr3d         ndarray       2x2x3: 12 elems, type `int64`, 96 bytes
arrDataType   BytesDType    |S1
arrObj        ndarray       3: 3 elems, type `int64`, 24 bytes
arrObj2       ndarray       3: 3 elems, type `int64`, 24 bytes
arrObjInt     ndarray       4: 4 elems, type `bool`, 4 bytes
numpy         module        <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [23]:
# linear Algebra
u = numpy.array([1, 0, 0, 2])
v = numpy.array([2, 4, 5, 6])


def vector_vector_multiplication(u, v):
    assert u.shape == v.shape, "vectors should be same size"

    n = v.shape[0]
    sum = 0
    for index in range(n):
        sum = sum + u[index] * v[index]
    return sum


vector_vector_multiplication(u, v)

numpy.dot(u, v)

np.int64(14)

In [24]:
# linear Algebra
U = numpy.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
v = numpy.array([1, 0.5, 2, 1])


def matrix_vector_multiplication(u, v):
    assert u.shape[1] == v.shape[0]

    nRow = numpy.shape(u)[0]
    result = numpy.zeros(nRow)

    for index in range(nRow):

        row = u[index]
        result[index] = vector_vector_multiplication(row, v)

    return result


print(matrix_vector_multiplication(U, v))
U.dot(v)

[20.   6.   8.5]


array([20. ,  6. ,  8.5])

In [25]:
# linear Algebra
U = numpy.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
V = numpy.array([[1, 1, 2], [0, 0.5, 1], [0, 2, 1], [2, 1, 0]])


def matrix_matrix_multiplication(u, v):

    result = numpy.zeros((u.shape[0], v.shape[1]))

    for colIndex in range(v.shape[1]):
        result[:, colIndex] = matrix_vector_multiplication(u, v[:, colIndex])

    return result


print(matrix_matrix_multiplication(U, V))
U.dot(V)

[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
# Identity martix
I = numpy.eye(3, 3)
print(V[[0, 1, 2]])
I.dot(V[[0, 1, 2]])

# Inverse matrix
vInverse = numpy.linalg.inv(V[[0, 1, 2]])

vInverse.dot(V[[0, 1, 2]])

[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]
V [[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]
 [2.  1.  0. ]]
[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])